# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 451 Unavailable For Legal Reasons
subtitle:
description:
author: Xeres
language: ja
timezone: Asia/Tokyo

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tech.xeres.jp
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# Extensions
## Plugins: https://hexo.io/plugins/

# Default Plugin: https://github.com/hexojs/hexo-renderer-marked
marked:
  breaks: false

# Plugin: https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# Plugin: https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml

  ## Themes: https://hexo.io/themes/
theme: miho
theme_config:
  # hexo-theme-miho
  # https://github.com/xeres/hexo-theme-miho

  # Favicon of your site
  favicon: /favicon-16x16.png

  # Header

  # Keywords of your site
  keywords: Xeres,451 Unavailable For Legal Reasons
  # Head headline
  header_title: 451 Unavailable For Legal Reasons
  # Head description
  header_description:
  # Link to your logo
  logo: images/logo.png
  # Link to your banner_img
  banner_img: images/banner.jpg
  # Menu setting
  #  name:                  Font Awesome icon
  #    title: Home          Title
  #    url: //minhow.com    Url, absolute or relative path
  #    target: true         Whether to jump out
  menu:
    home:
      title: ホーム
      url: /
      target: false
    archive:
      title: アーカイブ
      url: /archives
      target: false
    user:
      title: About
      url: /about
      target: false
  # Social setting, use to display social information
  #  name:                  Font Awesome icon
  #    title: Home          Icon title
  #    url: //minhow.com    Url, absolute or relative path
  #    target: true         Whether to jump out
  social:
    home:
      title: Blog
      url: //tech.xeres.jp
      target: false
    github:
      title: Github
      url: //github.com/xeres
      target: true
    twitter:
      title: Twitter
      url: //twitter.com/xerespm
      target: true
    #facebook:
    #google:
    #linkedin:

  # Content

  # Excerpt length
  excerpt_length: 190
  # Excerpt link
  excerpt_link: 続きを読む
  # New window open link
  open_new_link: false
  # Article default cover picture，size：350*150
  cover_picture: images/banner.jpg
  # Open background particles
  open_bg_particle: true
  # Open animation in homepage and head
  open_animation: false

  # Article

  # Open toc
  toc: true
  # Open share
  share: true
  shares:
    facebook:
      title: Facebook
    twitter:
      title: Twitter
    hatena:
      title: はてなブックマーク
    pocket:
      title: Pocket

  # Style customization
  style:
    # Main color tone
    main_color: '#aaa'

  # Reward

  reward:
    # 0-close, 1-All articles are rewarding, 2-Article's md file has reward:true attribute, only reward
    status: 0
  # Comments

  # disqus
  disqus: false

  # Analytics
  # google analytics
  google_analytics: UA-22861161-7

  # Footer

  # Access statistics
  access_counter:
    on: true
    site_uv: "UV:"
    site_pv: "PV:"

  # Copyright Information
  copyright: 2018 Xeres
